spring:
  application:
    name: soap-server

server:
  port: 8888

logging:
  pattern:
    console: "%cyan(%thread) %highlight(%-5level) %cyan(%logger{15}) - %msg %n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  info:
    git:
      mode: full
